version: '3.7'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
        - 2181

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_CREATE_TOPICS=test:1:1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_PORT=9092
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
    depends_on:
      - zookeeper

  local:
    image: kilo-franz
    build:
      dockerfile: Dockerfile
      context: .
      target: builder
    volumes:
      - .:/var/app
    environment:
      - KAFKA_CNX_STRING=kafka:9092
      - KAFKA_TOPIC=test
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_REGION=eu-west-1
      - AWS_DEBUG=1
      - AWS_ENDPOINT=http://localstack:4566
      - SM_HOST=http://localstack:4566
    depends_on:
      - kafka
      - localstack
    ports:
      - 8080

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=secretsmanager
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_REGION=eu-west-1
      - DEBUG=1
      - START_WEB=0
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - 4566
